### ISSUE TITLE
Add Create A Organization Page

### ISSUE THREAD

**Issue by sshh12** [AI-Global/ai-portal#14]
#### Add a page at `/organizations/create` for creating an organization on the portal. 

* Use `organization.model.js` and the [PRD](https://docs.google.com/document/d/1MCGk8TZpo9d7nncStZbRMbPAdmPeLNSTsUnzZvEkegg/edit) to find what the fields should be.
* This UI only, just leave a function to handle results and errors returns (like how it's done on the login page).
* Keep in mind that we will also have an organization editor page in the future so make parts of this reusable
* It should have search/multi-select for adding users

**Comment by sshh12** [comment]
Why was this closed?

**Comment by lucindan** [comment]
.....Idk....i think i pressed a button, sorry about that
